name: generate C code && binary
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Cython
      run: |
        python -m pip install cython

    - name: Run Cython
      run: |
        cython ${{ github.event.inputs.script }}.py --embed
        PYTHONLIBVER=python$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')$(python3-config --abiflags)
        gcc -Os $(python3-config --includes) ${{ github.event.inputs.script }}.c -o GUI/subs_manager $(python3-config --ldflags) -l$PYTHONLIBVER
      env:
        script: subs

